### ISSUE TITLE
Reload failed.

### ISSUE THREAD

**Issue by timpoismans** [mhamano/Qlik-Sense-Reload-Button#13]
Hello!

I'm having a weird issue with this extension. I'm running an application, fully tested at work, button worked fine. Now I set the application up at a client of mine and everything works fine, except the Reload Button. It keeps giving a "Reload failed!" result, while reloading through the script works perfectly.
Could this be version related? I'm working on Qlik Sense Desktop 3.2 SR2, my client just recently re-installed Qlik Sense Desktop from the website.

**Comment by mhamano** [comment]
The behavior of reload API changed in QS3.2 SR3 and I have fixed this extension to work on the QS version. Please guide your client to use the latest reload button.

**Comment by timpoismans** [comment]
Okay, had a feeling it was something like this, thanks!

**Comment by timpoismans** [comment]
So...

I updated my Qlik Sense Desktop to the latest version, which is 11.11.1
Client is on the same version, 11.11.1

Downloaded the updated extension and tested it on my version, where it works without issue.
Though the issue persists with the client and he keeps getting a 'Reload failed' when using the Reload button, while reloading through the script works fine.

Can I pressume the issue is not with the extension, but on the client's side?


Thanks in advance.

**Comment by mhamano** [comment]
It is also working fine on my QSD env in the latest version (June 2017 Patch 1), so the issue could be caused by something specific to your customer's env. Please check the following post and make sure that the extension is updated properly. Recreating the button might also work.

https://community.qlik.com/thread/170777
https://stackoverflow.com/questions/33637338/extension-doesnt-update

If there is an error on the extension, message should appear on the console of Chrome Dev Tool, so it is worth checking. Also, you can find the log file of the triggered reload task on C:\Users\%username%\Documents\Qlik\Sense\Log.
